Revert "Fix Issue 21299: Undefined reference to dmd.root.stringtable.StringValue!(Type).lstring()"
This reverts commit 32273e82ec9ba3f4022f03e7e12d5d4a384dc3ba.