Fix 21918 - Segfault for getParameterStorageClasses for invalid functions
The type of a `FuncDeclaration` is set to `TypeError` if the `auto`
inference fails. So `getParameters` has to check that the type is
actually a `TypeFunction`.

The additional check in `traits.d` prevents the invalid error message:
```
Error: parameter index must be in range 0..0 not 0
```