Fix Issue 21299: Undefined reference to dmd.root.stringtable.StringValue!(Type).lstring()
Alternative patch where instead of proactively fixing up instance
members when a template gets changed to a root instance, rather
propagate the `minst` as and when we run semantic on the nested
templates that still have a non-root `minst` from its scope.