Remove eager parsing error, move it to semantic
This is already checked in semantic, and this special case
only handle the rare case of having two successive variadic
template parameters.

The message will change from:
```
test.d(42): Error: variadic template parameter must be last
```

to:
```
test.d(42): Error: template `test.myTemplate(A..., B...)(A a, B b)` template tuple parameter must be last one
```