Fix CLang 6.0 build errors
(when building under Linux with `HOST_CXX=clang++`)

```
dmd/backend/go.c:123:18: error: case value evaluates to -1, which cannot be narrowed to type 'unsigned int' [-Wc++11-narrowing]
            case -1:                    /* not in flagtab[]     */
                 ^
  (CC)  BACK_OBJS  dmd/backend/dt.c
dmd/backend/go.c:157:18: error: case value evaluates to -1, which cannot be narrowed to type 'unsigned int' [-Wc++11-narrowing]
            case -1:                    /* not in flagtab[]     */
                 ^

dmd/backend/cod3.c:2707:22: error: case value evaluates to -1, which cannot be narrowed to type 'targ_size_t' (aka 'unsigned long') [-Wc++11-narrowing]
                case -1:
                     ^
```

I'm not so familiar with C++.
`flag` is `char`, but looking at the error message it seems that C++
does type widening automatically, so maybe `UINT_MAX` needs to be used
there too?