Add missing binding in SRCS
Some files were not part of `mak/SRCS`, and thus were not compiled it.

Since they are C bindings, it was unnoticed for a long time,
as most operations won't require the rare symbols this module defined.
However for things such as static array declarations,
the `__init` of the struct might be required, which triggers a linker error.

One simple way to trigger the issue was to use the function `timersub` defined in
`core.sys.linux.sys.time`:

---
src/ocean/core/UnitTestRunner.d:671: undefined reference to 'core.sys.linux.sys.time.timersub(const(core.sys.posix.sys.time.timeval*), const(core.sys.posix.sys.time.timeval*), core.sys.posix.sys.time.timeval*)'
---

The change to win{32,64}.mak was mandatory as the toolchain on the auto-tester cannot cope with that
number of files, and errors with "Command too long". DMD support 'response file' for that purpose.
Using `*` is a DigitalMars MAKE extension which will pass commands > 996 chars via the env.