Remove front-end dependency from dmd.errors
One of #23757 #23758 #23759 introduced forward reference regression when
compiling dmd one module at a time.

Remove the problematic import to break the cycle.

```
dmd/errors.d:227:1: error: enum dmd.errors.Classification is forward referenced when looking for 'error'
  227 | enum Classification : Color
      | ^
dmd/dtemplate.d:924:70: error: no property 'error' for type 'Classification'. Did you mean 'Classification.error' ?
  924 |     extern(D) final void printInstantiationTrace(Classification cl = Classification.error,
      |                                                                      ^
dmd/dtemplate.d:1130:27: error: function dmd.dtemplate.TemplateMixin.kind does not override any function
 1130 |     override const(char)* kind() const
      |                           ^
dmd/dtemplate.d:1135:19: error: function dmd.dtemplate.TemplateMixin.accept does not override any function
 1135 |     override void accept(Visitor v)
      |                   ^
```