Use supplemental error message for called function
By using a supplemental error message the compiler will output the
location of the called function on a separate line, with the same
syntax as a regular error message. This allows editors and IDEs to
generate links back to the source code without any special treatment
for these messages.

The following example:

```d
void foo() {}

@safe void main()
{
    foo();
}
```

Will now generate the following error message when compiled:

```
main.d(5): Error: @safe function D main cannot call @system function main.foo
main.d(1):        main.foo is declared here
```