Fix unittest error
i is of size_t which converts to long, but v is of type int, so cast is required
Error: cannot implicitly convert expression i * 2LU of type ulong to int  (barray.d:110)